name: 'divergent_shop_data'
version: '0.1.0'
config-version: 2
require-dbt-version: ">=1.0.0"
profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
target-path: "target"

clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"


seeds:
  divergent_shop_data:
    +full_refresh: true  # need to refresh seeds always as we are manually adding a column
    +post-hook:
      - "alter table {{ this }} add column ingest_timestamp_utc timestamp" 
      - "update {{ this }} set ingest_timestamp_utc = sysdate()"
